# Site settings
title: Формальные модели вычислений
email: maxim.krivchikov@gmail.com
description: "
М.А. Кривчиков, 2015 г.
"
baseurl: "/formal-models-2015/" # the subpath of your site, e.g. /blog/
url: "https://maxxk.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:  maxxk

# Build settings
markdown: kramdown
